tenant_client_id: CORE.DEV
core_api_host: http://localhost
services_port: 3001
auth_url: /auth/login
backend_url: api.core.com
api_url: http://localhost:3000/api
token_endpoint: https://login.microsoftonline.com
cert_pdf_sign_path: c:\CORE\certs\certificate.p12
cert_pdf_sign_type: p12

# Browser Pool Configuration
maxBrowsers: 1
maxPagesPerBrowser: 2
pageIdleTimeout: 60000  # 1 minute in milliseconds

#################################################################
# Backend database configuration
pg_host: "localhost"  # o la IP/hostname de tu servidor PostgreSQL
pg_port: 5432
pg_database: "core_backend_db"

# SSL configuration (si lo necesitas)
pg_ssl: true
pg_ssl_reject_unauthorized: true

# Connection pool settings
pg_min_connections: 2
pg_max_connections: 20
pg_idle_timeout_millis: 30000
pg_connection_timeout_millis: 5000

# Backend service configuration
backend_host: "0.0.0.0"
backend_port: 3000
service_name: "core-backend"
node_env: "development"
log_level: "info"

# Retention settings
health_check_interval: 60000
#################################################################