# Company Core Development Environment Configuration
tenant:
  client_id: CORE.DEV
  name: "Core Development Environment"
  environment: development

# Services set for the Core Development Environment
services:
  - name: core-services
    enabled: true
    host: http://localhost
    port: 3001
    endpoints:
      auth: /auth/login
      api: /api
      health_check: /health
    browser_pool:
      max_browsers: 1
      pdf_generation:
        max_pages_per_browser: 2
        page_idle_timeout: 60000
    certificates:
      pdf_signing:
        path: c:\CORE\certs\certificate.p12
        type: p12

  - name: core-backend
    enabled: true
    host: http://localhost
    port: 3000
    endpoints:
      auth: /auth/login
      api: /api
      health_check: /health
    database:
      host: localhost
      port: 5432
      name: core_dev
      ssl:
        enabled: true
        reject_unauthorized: true
      pool:
        min: 2
        max: 20
        idle_timeout: 30000
        connection_timeout: 5000
    monitoring:
      health_check_interval: 60000
      log_level: info

# External services used by the Core Development Environment
external_services:
  - name: ms365
    type: oauth2
    endpoints:
      token: https://login.microsoftonline.com

# Servers configuration for the Core Development Environment
servers:
  - name: cul-core-nodejs
    hostname: cul-core-nodejs
    monitoring:
      heartbeat: false
      metrics: false
      logs: false
    tags:
      - windows
      - development
      
  - name: cul-core-dock01
    hostname: cul-core-dock01
    monitoring:
      heartbeat: true
      metrics: false
      logs: false
    tags:
      - linux
      - development
